-- =====================================================
-- Blog CMS Seed Data for Development
-- =====================================================
-- This file contains sample data for testing the blog CMS
-- Run after the migration: psql $DATABASE_URL -f seed_blog.sql
-- =====================================================

-- Create test users if they don't exist
DO $$
DECLARE
  admin_user_id UUID;
  author1_id UUID;
  author2_id UUID;
  test_user_id UUID;
BEGIN
  -- Create admin user
  INSERT INTO users (id, email, name, role)
  VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'admin@dependablecalls.com', 'Admin User', 'admin')
  ON CONFLICT (id) DO NOTHING;
  
  admin_user_id := 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11';
  
  -- Create author users
  INSERT INTO users (id, email, name, role)
  VALUES 
    ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'john@dependablecalls.com', 'John Doe', 'supplier'),
    ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'jane@dependablecalls.com', 'Jane Smith', 'supplier'),
    ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'testuser@example.com', 'Test User', 'supplier')
  ON CONFLICT (id) DO NOTHING;
  
  author1_id := 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12';
  author2_id := 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13';
  test_user_id := 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14';
  
  -- Create admin record
  INSERT INTO admins (user_id, created_at)
  VALUES (admin_user_id, NOW())
  ON CONFLICT (user_id) DO NOTHING;
END $$;

-- Create blog authors
INSERT INTO blog_authors (id, user_id, display_name, bio, avatar_url, social_links)
VALUES 
  (
    'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'Admin Team',
    'The Dependable Calls admin team manages platform updates and announcements.',
    'https://ui-avatars.com/api/?name=Admin+Team&background=3B82F6&color=fff',
    '{"twitter": "@dependablecalls", "linkedin": "dependablecalls"}'::jsonb
  ),
  (
    'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
    'John Doe',
    'John is a pay-per-call expert with over 10 years of experience in affiliate marketing.',
    'https://ui-avatars.com/api/?name=John+Doe&background=10B981&color=fff',
    '{"twitter": "@johndoe", "linkedin": "john-doe"}'::jsonb
  ),
  (
    'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
    'Jane Smith',
    'Jane specializes in lead generation strategies and conversion optimization.',
    'https://ui-avatars.com/api/?name=Jane+Smith&background=F59E0B&color=fff',
    '{"twitter": "@janesmith", "linkedin": "jane-smith"}'::jsonb
  )
ON CONFLICT (id) DO NOTHING;

-- Create sample blog posts
INSERT INTO blog_posts (
  id, slug, title, subtitle, content, excerpt, featured_image_url,
  author_id, status, published_at, metadata, view_count, reading_time_minutes
)
VALUES 
  (
    'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'welcome-to-dependable-calls-blog',
    'Welcome to the Dependable Calls Blog',
    'Your source for pay-per-call insights and platform updates',
    E'# Welcome to Dependable Calls\n\nWe''re excited to launch our new blog where we''ll share:\n\n## Platform Updates\nStay informed about new features, improvements, and system updates.\n\n## Industry Insights\nLearn from our analysis of pay-per-call trends and best practices.\n\n## Success Stories\nDiscover how our users are achieving success with Dependable Calls.\n\n## Tutorials & Guides\nStep-by-step instructions to help you maximize your results.\n\n### What is Pay-Per-Call?\n\nPay-per-call is a performance marketing model where advertisers pay for qualified phone calls generated by publishers. It''s particularly effective for industries where customers prefer phone conversations:\n\n- **Home Services**: Plumbing, HVAC, roofing\n- **Legal Services**: Personal injury, bankruptcy, criminal defense\n- **Insurance**: Auto, home, life insurance quotes\n- **Healthcare**: Dental, medical procedures, rehabilitation\n\n### Why Dependable Calls?\n\nOur platform provides:\n\n1. **Real-time Tracking**: Monitor your calls as they happen\n2. **Advanced Fraud Detection**: Protect your campaigns from invalid traffic\n3. **Flexible Routing**: Send calls to the right buyers at the right time\n4. **Detailed Analytics**: Make data-driven decisions\n5. **Reliable Payments**: Get paid on time, every time\n\n### Getting Started\n\nReady to start? Here''s how:\n\n1. Sign up for an account\n2. Set up your first campaign\n3. Configure call tracking numbers\n4. Start receiving calls\n5. Track performance in real-time\n\nWe''re here to help you succeed. Check back regularly for new content!',
    'Welcome to the Dependable Calls blog - your source for pay-per-call insights, platform updates, and success stories.',
    'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?w=1600&h=900&fit=crop',
    'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'published',
    NOW() - INTERVAL '7 days',
    '{"seo_title": "Welcome to Dependable Calls Blog | Pay-Per-Call Platform", "seo_description": "Discover pay-per-call insights, platform updates, and success stories on the Dependable Calls blog."}'::jsonb,
    156,
    3
  ),
  (
    'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
    'top-5-pay-per-call-verticals-2024',
    'Top 5 Pay-Per-Call Verticals for 2024',
    'Discover the most profitable industries for pay-per-call marketing',
    E'# Top 5 Pay-Per-Call Verticals for 2024\n\nAs we move through 2024, certain industries continue to dominate the pay-per-call landscape. Here are the top 5 verticals showing exceptional performance:\n\n## 1. Home Services\n\n**Average Payout: $35-$125 per call**\n\nHome services remain the backbone of pay-per-call:\n\n- **HVAC**: Peak seasons drive high demand\n- **Plumbing**: Emergency calls command premium rates\n- **Roofing**: Storm season creates surge opportunities\n- **Pest Control**: Recurring revenue potential\n\n### Key Success Factors:\n- Local SEO optimization\n- Seasonal campaign adjustments\n- 24/7 call availability\n\n## 2. Legal Services\n\n**Average Payout: $75-$500 per call**\n\nLegal verticals offer some of the highest payouts:\n\n- **Personal Injury**: Motor vehicle accidents, slip & fall\n- **Mass Tort**: Camp Lejeune, talcum powder, roundup\n- **Criminal Defense**: DUI, domestic violence\n- **Bankruptcy**: Chapter 7 and Chapter 13 filings\n\n### Compliance Requirements:\n- TCPA compliance mandatory\n- State bar advertising rules\n- Clear disclaimers required\n\n## 3. Insurance\n\n**Average Payout: $15-$75 per call**\n\nInsurance remains stable with consistent demand:\n\n- **Auto Insurance**: High volume, moderate payouts\n- **Health Insurance**: ACA enrollment periods\n- **Life Insurance**: Final expense popular with seniors\n- **Medicare**: Advantage plans and supplements\n\n## 4. Financial Services\n\n**Average Payout: $25-$150 per call**\n\nGrowing sector with diverse opportunities:\n\n- **Tax Relief**: IRS debt resolution\n- **Debt Consolidation**: Credit card and personal loans\n- **Business Funding**: MCA and equipment financing\n- **Credit Repair**: Score improvement services\n\n## 5. Healthcare & Wellness\n\n**Average Payout: $20-$200 per call**\n\nExpanding vertical with aging population:\n\n- **Dental**: Implants and cosmetic procedures\n- **Vision**: LASIK and cataract surgery\n- **Hearing**: Hearing aids and testing\n- **Addiction Treatment**: Rehab and recovery centers\n\n## Optimization Tips for All Verticals\n\n### 1. Quality Over Quantity\nFocus on generating qualified calls rather than volume. Pre-qualification saves everyone time.\n\n### 2. Geographic Targeting\nSome verticals perform better in specific regions. Use geo-targeting to maximize conversions.\n\n### 3. Time-of-Day Optimization\nDifferent verticals have different peak hours. Adjust your campaigns accordingly.\n\n### 4. Compliance First\nStay updated on regulations. Non-compliance can shut down campaigns instantly.\n\n## Looking Ahead\n\nThe pay-per-call industry continues to evolve. Success requires:\n\n- Staying informed about industry trends\n- Testing new traffic sources\n- Building strong buyer relationships\n- Maintaining compliance standards\n\nWhich vertical are you focusing on? Let us know in the comments!',
    'Explore the most profitable pay-per-call verticals for 2024, including home services, legal, insurance, and more.',
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1600&h=900&fit=crop',
    'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
    'published',
    NOW() - INTERVAL '3 days',
    '{"seo_title": "Top 5 Pay-Per-Call Verticals 2024 | High-Paying Industries", "seo_description": "Discover the most profitable pay-per-call verticals for 2024. Learn average payouts and optimization strategies for each industry."}'::jsonb,
    342,
    5
  ),
  (
    'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
    'fraud-prevention-best-practices',
    'Fraud Prevention Best Practices for Pay-Per-Call',
    'Protect your campaigns from invalid traffic and fraudulent calls',
    E'# Fraud Prevention Best Practices for Pay-Per-Call\n\nFraud prevention is crucial for maintaining profitable pay-per-call campaigns. Here''s how to protect your business:\n\n## Common Types of Pay-Per-Call Fraud\n\n### 1. Repeat Callers\nThe same person calling multiple times to generate commissions.\n\n**Detection Methods:**\n- ANI (Automatic Number Identification) tracking\n- Voice fingerprinting technology\n- Call pattern analysis\n\n### 2. Call Centers\nOrganized operations making bulk calls with scripts.\n\n**Red Flags:**\n- High call volume from single location\n- Similar call durations\n- Background noise patterns\n\n### 3. Incentivized Traffic\nPaying users to make calls regardless of intent.\n\n**Warning Signs:**\n- Unusually high conversion rates\n- Short call durations\n- No follow-through on appointments\n\n## Prevention Strategies\n\n### Real-Time Monitoring\n\nImplement these monitoring practices:\n\n1. **Live Call Listening**\n   - Random quality checks\n   - Flagged number monitoring\n   - Suspicious pattern alerts\n\n2. **Analytics Dashboard**\n   - Geographic heat maps\n   - Conversion funnel analysis\n   - Publisher performance metrics\n\n### Technology Solutions\n\n```javascript\n// Example fraud detection logic\nconst fraudIndicators = {\n  repeatCaller: checkANIHistory(callerNumber),\n  shortDuration: callDuration < minimumThreshold,\n  suspiciousPattern: analyzeCallPattern(publisherId),\n  geoMismatch: !validateGeolocation(callerIP, callerANI)\n};\n\nif (Object.values(fraudIndicators).some(indicator => indicator)) {\n  flagForReview(callId);\n}\n```\n\n### Publisher Vetting\n\n**Initial Screening:**\n- Business verification\n- Traffic source disclosure\n- Reference checks\n- Test period requirements\n\n**Ongoing Monitoring:**\n- Quality scores\n- Conversion tracking\n- Customer feedback\n- Mystery shopping\n\n## Building a Fraud Prevention Framework\n\n### 1. Set Clear Guidelines\n\nDocument and communicate:\n- Acceptable traffic sources\n- Prohibited practices\n- Quality standards\n- Penalty structure\n\n### 2. Use Technology Wisely\n\nLeverage tools for:\n- Call recording and transcription\n- AI-powered anomaly detection\n- Behavioral analysis\n- Cross-reference databases\n\n### 3. Create Feedback Loops\n\nEstablish processes for:\n- Buyer complaint handling\n- Publisher dispute resolution\n- Continuous improvement\n- Industry intelligence sharing\n\n## Case Study: Reducing Fraud by 87%\n\nOne of our enterprise clients implemented our fraud prevention framework:\n\n**Before:**\n- 23% invalid call rate\n- $45,000 monthly fraud losses\n- 15% buyer churn\n\n**After:**\n- 3% invalid call rate\n- $6,000 monthly fraud losses\n- 2% buyer churn\n\n**Key Actions:**\n1. Implemented real-time ANI checking\n2. Required publisher phone verification\n3. Set minimum call duration requirements\n4. Created fraud score algorithm\n\n## Best Practices Checklist\n\n✅ Real-time call monitoring\n✅ Multi-layer verification\n✅ Publisher vetting process\n✅ Clear terms of service\n✅ Regular audits\n✅ Buyer feedback integration\n✅ Technology stack updates\n✅ Team training programs\n\n## Moving Forward\n\nFraud prevention is an ongoing process. Stay vigilant, adapt to new threats, and maintain open communication with your partners.\n\nRemember: It''s better to reject suspicious traffic than to risk your buyer relationships.\n\nQuestions about fraud prevention? Contact our support team for personalized guidance.',
    'Learn essential fraud prevention strategies for pay-per-call campaigns, including detection methods and technology solutions.',
    'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1600&h=900&fit=crop',
    'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
    'published',
    NOW() - INTERVAL '1 day',
    '{"seo_title": "Pay-Per-Call Fraud Prevention Guide | Best Practices 2024", "seo_description": "Protect your pay-per-call campaigns from fraud. Learn detection methods, prevention strategies, and technology solutions."}'::jsonb,
    289,
    7
  ),
  (
    'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14',
    'setting-up-your-first-campaign',
    'Setting Up Your First Pay-Per-Call Campaign',
    'A step-by-step guide for beginners',
    E'# Setting Up Your First Pay-Per-Call Campaign\n\nStarting your first pay-per-call campaign can seem daunting. This guide will walk you through each step:\n\n## Step 1: Choose Your Vertical\n\nSelect an industry based on:\n- Your existing knowledge\n- Market demand\n- Payout potential\n- Competition level\n\n**Beginner-Friendly Verticals:**\n- Home services (HVAC, plumbing)\n- Auto insurance\n- Tax relief\n\n## Step 2: Find Buyers\n\nBefore generating calls, secure buyers:\n\n### Direct Advertisers\n- Higher payouts\n- Stable relationships\n- Specific requirements\n\n### Networks/Aggregators\n- Easier approval\n- Multiple options\n- Lower payouts\n\n## Step 3: Set Up Tracking\n\n### Phone Numbers\n- Use local or toll-free numbers\n- Dynamic number insertion (DNI)\n- Call recording capabilities\n\n### Analytics Platform\n- Real-time reporting\n- Conversion tracking\n- ROI calculation\n\n## Step 4: Create Your Campaign\n\n### Target Audience\nDefine your ideal caller:\n- Demographics\n- Geographic location\n- Intent signals\n- Pain points\n\n### Traffic Sources\n\n**Paid Search (Google Ads)**\n```\nPros: High intent, scalable\nCons: Expensive, competitive\nBudget: $50-100/day minimum\n```\n\n**SEO/Content Marketing**\n```\nPros: Free traffic, authority building\nCons: Time-intensive, slow results\nTimeline: 3-6 months\n```\n\n**Social Media**\n```\nPros: Targeting options, creative freedom\nCons: Lower intent, compliance issues\nPlatforms: Facebook, TikTok, Instagram\n```\n\n## Step 5: Optimize Your Funnel\n\n### Landing Page Elements\n\n1. **Headline**: Clear value proposition\n2. **Call-to-Action**: Prominent phone number\n3. **Trust Signals**: Reviews, badges, testimonials\n4. **Urgency**: Limited time offers\n5. **Mobile Optimization**: Click-to-call functionality\n\n### A/B Testing Ideas\n- Headlines and subheadings\n- Button colors and text\n- Form fields vs. direct call\n- Images and videos\n- Trust elements placement\n\n## Step 6: Launch and Monitor\n\n### Soft Launch Strategy\n\n**Week 1**: \n- Start with $50/day budget\n- Monitor every call\n- Note quality issues\n\n**Week 2**:\n- Optimize based on data\n- Increase budget if profitable\n- Test new ad copies\n\n**Week 3**:\n- Scale winning campaigns\n- Pause underperformers\n- Negotiate better payouts\n\n### Key Metrics to Track\n\n| Metric | Target | Importance |\n|--------|--------|------------|\n| Cost Per Call | < 50% of payout | Critical |\n| Conversion Rate | > 60% | High |\n| Average Call Duration | > 90 seconds | High |\n| ROI | > 30% | Critical |\n\n## Common Mistakes to Avoid\n\n### 1. Skipping Testing\nAlways start small and test before scaling.\n\n### 2. Ignoring Quality\nBad calls hurt buyer relationships.\n\n### 3. Poor Tracking\nYou can''t optimize what you don''t measure.\n\n### 4. Compliance Violations\nKnow and follow all regulations.\n\n## Your 30-Day Action Plan\n\n**Days 1-7**: Research and Planning\n- Choose vertical\n- Research competitors\n- Find buyers\n- Set up tracking\n\n**Days 8-14**: Campaign Creation\n- Build landing pages\n- Create ad campaigns\n- Set up call flows\n- Test everything\n\n**Days 15-21**: Launch and Optimize\n- Start with small budget\n- Monitor performance\n- Make adjustments\n- Document learnings\n\n**Days 22-30**: Scale and Expand\n- Increase budget on winners\n- Test new traffic sources\n- Negotiate better rates\n- Plan next campaign\n\n## Resources and Tools\n\n### Essential Tools:\n- **Call Tracking**: Dependable Calls Platform\n- **Landing Pages**: Unbounce, ClickFunnels\n- **Analytics**: Google Analytics, CallRail\n- **Compliance**: TCPA guidelines, Jornaya\n\n### Learning Resources:\n- Industry forums and communities\n- Webinars and conferences\n- Case studies and success stories\n- Mentorship programs\n\n## Success Story\n\n*"I started with a $500 budget in home services. By following this framework, I scaled to $10,000/month in profit within 6 months. The key was starting small, testing everything, and building strong buyer relationships."* - Sarah M., Affiliate Marketer\n\n## Next Steps\n\n1. **Choose your vertical** based on the criteria above\n2. **Sign up** for Dependable Calls to get your tracking numbers\n3. **Connect with buyers** in our marketplace\n4. **Launch your first campaign** following this guide\n\nNeed help? Our support team is here to guide you through every step.\n\n**Ready to start? [Sign up now](https://dependablecalls.com/signup) and get your first tracking number free!**',
    'Complete guide to launching your first pay-per-call campaign, from choosing a vertical to scaling your success.',
    'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1600&h=900&fit=crop',
    'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'published',
    NOW() - INTERVAL '5 days',
    '{"seo_title": "How to Start a Pay-Per-Call Campaign | Beginner Guide 2024", "seo_description": "Step-by-step guide to setting up your first pay-per-call campaign. Learn vertical selection, buyer finding, and optimization strategies."}'::jsonb,
    521,
    8
  ),
  (
    'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15',
    'real-time-call-tracking-benefits',
    'The Power of Real-Time Call Tracking',
    'How instant data transforms campaign performance',
    E'# The Power of Real-Time Call Tracking\n\nIn pay-per-call marketing, information delay equals money lost. Real-time call tracking transforms how you manage campaigns.\n\n## Why Real-Time Matters\n\n### Instant Decision Making\n\n**Traditional Tracking:**\n- Daily or hourly reports\n- Delayed optimization\n- Missed opportunities\n- Reactive management\n\n**Real-Time Tracking:**\n- Immediate insights\n- Proactive adjustments\n- Opportunity capture\n- Predictive actions\n\n## Key Benefits of Real-Time Tracking\n\n### 1. Fraud Detection\n\nCatch fraudulent activity as it happens:\n- Duplicate calls flagged instantly\n- Suspicious patterns identified\n- Immediate blocking capability\n- Protect buyer relationships\n\n### 2. Budget Optimization\n\n```\nReal-Time Scenario:\n10:00 AM - Campaign launches at $50 CPL\n10:30 AM - CPL jumps to $120\n10:31 AM - Auto-pause triggered\n10:45 AM - Issue identified and fixed\n11:00 AM - Campaign resumes profitably\n\nSaved: $840 in potential losses\n```\n\n### 3. Quality Control\n\nMonitor call quality instantly:\n- Duration tracking\n- Conversion monitoring\n- Caller intent analysis\n- Publisher performance\n\n## Real-Time Features That Drive Results\n\n### Live Dashboard\n\n**Essential Metrics:**\n- Active calls counter\n- Conversion rates by source\n- Current spend vs. revenue\n- Publisher performance ranks\n\n### Instant Alerts\n\nSet notifications for:\n- High-value calls\n- Conversion rate drops\n- Budget thresholds\n- Unusual activity patterns\n\n### Dynamic Routing\n\nRoute calls based on:\n- Buyer availability\n- Geographic preferences\n- Call value scoring\n- Time-based rules\n\n## Implementation Guide\n\n### Step 1: Set Up Your Dashboard\n\nCustomize views for:\n- **Overview**: Key metrics at a glance\n- **Campaign View**: Detailed performance\n- **Publisher View**: Partner tracking\n- **Buyer View**: Client satisfaction\n\n### Step 2: Configure Alerts\n\n```javascript\n// Example alert configuration\nconst alertRules = [\n  {\n    metric: "conversionRate",\n    condition: "below",\n    threshold: 0.6,\n    action: "email + pause"\n  },\n  {\n    metric: "costPerConversion", \n    condition: "above",\n    threshold: 80,\n    action: "slack notification"\n  }\n];\n```\n\n### Step 3: Create Response Protocols\n\nDocument actions for common scenarios:\n\n**Conversion Drop Protocol:**\n1. Check buyer availability\n2. Review recent calls\n3. Contact top publishers\n4. Adjust targeting if needed\n\n## Case Studies\n\n### Case 1: Insurance Broker Saves $15,000\n\n**Challenge**: Overnight fraud attack\n**Solution**: Real-time alerts triggered at 2 AM\n**Action**: Auto-blocked suspicious sources\n**Result**: Prevented $15,000 in fraudulent charges\n\n### Case 2: Home Services Scales 300%\n\n**Challenge**: Identifying profitable hours\n**Solution**: Real-time heat mapping\n**Action**: Shifted budget to peak hours\n**Result**: 300% ROI improvement\n\n## Advanced Real-Time Strategies\n\n### Predictive Optimization\n\nUse real-time data for:\n- Demand forecasting\n- Budget allocation\n- Staffing decisions\n- Inventory management\n\n### Multi-Touch Attribution\n\nTrack the complete journey:\n- First touch: Ad click\n- Second touch: Form fill\n- Third touch: Phone call\n- Attribution: Weighted model\n\n### API Integration\n\nConnect real-time data to:\n- CRM systems\n- Business intelligence tools\n- Marketing automation\n- Financial platforms\n\n## Building a Real-Time Culture\n\n### Team Training\n\nEnsure your team can:\n- Read dashboards effectively\n- Respond to alerts quickly\n- Make data-driven decisions\n- Document learnings\n\n### Process Documentation\n\nCreate playbooks for:\n- Alert responses\n- Optimization workflows  \n- Escalation procedures\n- Performance reviews\n\n## ROI of Real-Time Tracking\n\n### Typical Results:\n\n| Metric | Before Real-Time | After Real-Time | Improvement |\n|--------|-----------------|-----------------|-------------|\n| Fraud Rate | 15% | 3% | -80% |\n| Response Time | 4 hours | 5 minutes | -98% |\n| Campaign ROI | 25% | 65% | +160% |\n| Buyer Satisfaction | 72% | 91% | +26% |\n\n## Getting Started with Real-Time\n\n### Week 1: Foundation\n- Set up dashboards\n- Configure basic alerts\n- Train team members\n\n### Week 2: Optimization\n- Refine alert thresholds\n- Create response protocols\n- Test automation rules\n\n### Week 3: Advanced Features\n- Implement API connections\n- Set up custom reports\n- Launch predictive models\n\n### Week 4: Scale\n- Roll out to all campaigns\n- Document best practices\n- Plan future enhancements\n\n## The Future of Real-Time\n\nEmerging capabilities:\n- AI-powered predictions\n- Voice analysis\n- Sentiment scoring\n- Automated optimization\n\nStay ahead by embracing real-time tracking today.\n\n**Ready to experience real-time tracking? [Start your free trial](https://dependablecalls.com/signup) and see the difference instantly.**',
    'Discover how real-time call tracking revolutionizes pay-per-call campaigns with instant insights and automated optimization.',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&h=900&fit=crop',
    'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
    'published',
    NOW() - INTERVAL '2 days',
    '{"seo_title": "Real-Time Call Tracking Benefits | Pay-Per-Call Analytics", "seo_description": "Learn how real-time call tracking improves campaign performance, prevents fraud, and maximizes ROI in pay-per-call marketing."}'::jsonb,
    187,
    6
  ),
  (
    'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16',
    'draft-post-example',
    'Understanding Call Attribution Models',
    'A deep dive into attribution strategies',
    E'# Understanding Call Attribution Models\n\nThis is a draft post about call attribution models...\n\n## Introduction\n\nCall attribution is critical for understanding which marketing efforts drive phone calls.\n\n## Types of Attribution Models\n\n1. First Touch\n2. Last Touch  \n3. Multi-Touch\n4. Time Decay\n5. Custom Models\n\n[Content continues...]',
    'Learn about different call attribution models and how to choose the right one for your campaigns.',
    NULL,
    'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
    'draft',
    NULL,
    '{"seo_title": "Call Attribution Models Explained", "seo_description": "Understanding different attribution models for pay-per-call campaigns."}'::jsonb,
    0,
    4
  );

-- Link posts to categories
INSERT INTO blog_post_categories (post_id, category_id)
SELECT 
  p.id as post_id,
  c.id as category_id
FROM blog_posts p
CROSS JOIN blog_categories c
WHERE 
  (p.slug = 'welcome-to-dependable-calls-blog' AND c.slug = 'announcements') OR
  (p.slug = 'top-5-pay-per-call-verticals-2024' AND c.slug = 'industry-insights') OR
  (p.slug = 'fraud-prevention-best-practices' AND c.slug = 'best-practices') OR
  (p.slug = 'setting-up-your-first-campaign' AND c.slug = 'tutorials') OR
  (p.slug = 'real-time-call-tracking-benefits' AND c.slug = 'industry-insights') OR
  (p.slug = 'draft-post-example' AND c.slug = 'tutorials');

-- Link posts to tags
INSERT INTO blog_post_tags (post_id, tag_id)
SELECT 
  p.id as post_id,
  t.id as tag_id
FROM blog_posts p
CROSS JOIN blog_tags t
WHERE 
  (p.slug = 'welcome-to-dependable-calls-blog' AND t.slug IN ('announcements', 'getting-started')) OR
  (p.slug = 'top-5-pay-per-call-verticals-2024' AND t.slug IN ('industry-insights', 'affiliate-marketing')) OR
  (p.slug = 'fraud-prevention-best-practices' AND t.slug IN ('best-practices', 'tips-tricks')) OR
  (p.slug = 'setting-up-your-first-campaign' AND t.slug IN ('getting-started', 'tutorials')) OR
  (p.slug = 'real-time-call-tracking-benefits' AND t.slug IN ('updates', 'best-practices')) OR
  (p.slug = 'draft-post-example' AND t.slug IN ('tutorials', 'lead-generation'));

-- Add some test comments (optional - for Phase 2)
INSERT INTO blog_comments (
  post_id, user_id, content, content_sanitized, status, ip_address, user_agent
)
SELECT
  p.id as post_id,
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14' as user_id,
  'Great article! This really helped me understand the basics.' as content,
  'Great article! This really helped me understand the basics.' as content_sanitized,
  'approved' as status,
  '192.168.1.100'::inet as ip_address,
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)' as user_agent
FROM blog_posts p
WHERE p.slug = 'setting-up-your-first-campaign';

-- Update search vectors for all posts
UPDATE blog_posts
SET search_vector = 
  setweight(to_tsvector('english', COALESCE(title, '')), 'A') ||
  setweight(to_tsvector('english', COALESCE(subtitle, '')), 'B') ||
  setweight(to_tsvector('english', COALESCE(content, '')), 'C');

-- Add reading time for posts that don't have it calculated
UPDATE blog_posts
SET reading_time_minutes = GREATEST(1, CEIL(array_length(string_to_array(content, ' '), 1)::FLOAT / 200))
WHERE reading_time_minutes IS NULL;