version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dce-website
    ports:
      - '4173:4173'
    environment:
      NODE_ENV: production
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
      VITE_SENTRY_DSN: ${VITE_SENTRY_DSN}
      VITE_APP_VERSION: ${VITE_APP_VERSION:-1.0.0}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4173/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - dce-network

  # Development environment with hot reload
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dce-website-dev
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
    env_file:
      - .env
    networks:
      - dce-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: dce-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - dce-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: dce-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-defaultpass}
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - dce-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 30s
      timeout: 3s
      retries: 5

networks:
  dce-network:
    driver: bridge

volumes:
  redis-data: