[build]
  publish = "dist"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--prefix=/dev/null"

# Production settings
[context.production]
  command = "npm run build"
  
[context.production.environment]
  NODE_ENV = "production"

# Staging/develop branch settings
[context.develop]
  command = "npm run build"
  
[context.develop.environment]
  NODE_ENV = "staging"

# Branch deploy previews
[context.branch-deploy]
  command = "npm run build"

# Security headers - Hardened CSP without unsafe-inline
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), serial=(), bluetooth=(), magnetometer=(), gyroscope=(), accelerometer=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # CSP without nonces for now
    Content-Security-Policy = """
      default-src 'none';
      script-src 'self' 'sha256-+3GXJ2G3I/IXulZBI6geN6c88hWeJ4IS6Q5C8bT3emk=' https://js.stripe.com https://cdn.jsdelivr.net;
      script-src-elem 'self' 'sha256-+3GXJ2G3I/IXulZBI6geN6c88hWeJ4IS6Q5C8bT3emk=' https://js.stripe.com https://cdn.jsdelivr.net;
      script-src-attr 'none';
      style-src 'self' https://fonts.googleapis.com;
      style-src-elem 'self' https://fonts.googleapis.com;
      style-src-attr 'none';
      font-src 'self' https://fonts.gstatic.com data:;
      img-src 'self' data: https: blob:;
      media-src 'self';
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.stripe.com https://*.sentry.io;
      frame-src https://js.stripe.com https://checkout.stripe.com;
      frame-ancestors 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://checkout.stripe.com;
      manifest-src 'self';
      worker-src 'self' blob:;
      child-src 'self' blob:;
      report-to csp-violations;
      report-uri /.netlify/functions/csp-report;
      upgrade-insecure-requests;
    """
    # Report-To header for CSP v3 violation reporting
    Report-To = """{"group":"csp-violations","max_age":10886400,"endpoints":[{"url":"/.netlify/functions/csp-report"}]}"""
    # Additional security headers
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"

# Static assets with security headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "same-origin"
    Referrer-Policy = "no-referrer"

# JavaScript files - strict security
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "same-origin"
    Referrer-Policy = "no-referrer"

# CSS files - strict security
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "same-origin"
    Referrer-Policy = "no-referrer"

# Font files - optimized caching
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "cross-origin"
    Access-Control-Allow-Origin = "*"

# Image files - secure caching
[[headers]]
  for = "*.{png,jpg,jpeg,gif,svg,webp,avif,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "same-origin"
    Referrer-Policy = "no-referrer"

# SVG files - additional security
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/svg+xml; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "same-origin"
    Referrer-Policy = "no-referrer"

# HTML files - no caching for dynamic content
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "same-origin"

# API endpoints - no caching, strict security  
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "same-origin"
    Referrer-Policy = "no-referrer"

# Netlify functions - secure headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "same-origin"
    Referrer-Policy = "no-referrer"

# SPA routing - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Health check endpoint
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# API redirects to edge functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Blog API redirects with path parameters
[[redirects]]
  from = "/api/blog/*"
  to = "/.netlify/functions/blog-api/:splat"
  status = 200

# Uptime monitoring webhook endpoint
[[redirects]]
  from = "/webhooks/uptime"
  to = "/.netlify/functions/uptime-webhook"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://dependablecalls.com/*"
  to = "https://dependablecalls.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.dependablecalls.com/*"
  to = "https://dependablecalls.com/:splat"
  status = 301
  force = true

# Redirect www to non-www
[[redirects]]
  from = "https://www.dependablecalls.com/*"
  to = "https://dependablecalls.com/:splat"
  status = 301
  force = true

# Edge Functions - temporarily disabled for deployment
# [[edge_functions]]
#   function = "auth-middleware"
#   path = "/dashboard/*"

# [[edge_functions]]
#   function = "rate-limiter"
#   path = "/api/*"

# Form handling
# Plugin configuration removed - invalid syntax