[build]
  publish = "dist"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--prefix=/dev/null"

# Production settings
[context.production]
  command = "npm run build"
  
[context.production.environment]
  NODE_ENV = "production"

# Staging/develop branch settings
[context.develop]
  command = "npm run build"
  
[context.develop.environment]
  NODE_ENV = "staging"

# Branch deploy previews
[context.branch-deploy]
  command = "npm run build"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://js.stripe.com https://cdn.jsdelivr.net;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.stripe.com https://*.sentry.io;
      frame-src https://js.stripe.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      upgrade-insecure-requests;
    """

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA routing - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "user"], Country = ["US", "CA"]}

# Health check endpoint
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# API redirects to edge functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://dependablecalls.com/*"
  to = "https://dependablecalls.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.dependablecalls.com/*"
  to = "https://dependablecalls.com/:splat"
  status = 301
  force = true

# Redirect www to non-www
[[redirects]]
  from = "https://www.dependablecalls.com/*"
  to = "https://dependablecalls.com/:splat"
  status = 301
  force = true

# Edge Functions
[[edge_functions]]
  function = "auth-middleware"
  path = "/dashboard/*"

[[edge_functions]]
  function = "rate-limiter"
  path = "/api/*"

# Form handling
[plugins]
  [[plugins.inputs]]
    command = "npm run build"