# Container Security Monitor Configuration
# =====================================

# Basic monitoring settings
monitor_interval: 30  # seconds between monitoring cycles
report_interval: 300  # seconds between security reports (5 minutes)
retention_days: 30    # days to retain security events

# Container selection
container_patterns:
  - "dce-*"         # DCE application containers
  - "*-nginx"       # Nginx containers
  - "*-redis"       # Redis containers

# Monitoring features
network_monitoring: true
file_monitoring: true
process_monitoring: true
behavioral_analysis: true

# Alert configuration
alert_webhook: null  # Set via environment variable ALERT_WEBHOOK

# Resource thresholds for anomaly detection
cpu_threshold: 80.0          # CPU usage percentage
memory_threshold: 80.0       # Memory usage percentage
network_threshold_mbps: 100.0  # Network traffic in Mbps
file_change_threshold: 100   # Number of file changes per interval

# Security policies
allowed_ports:
  - 80    # HTTP
  - 443   # HTTPS
  - 6379  # Redis
  - 8080  # Alternative HTTP

# Processes that should not be running in containers
blocked_processes:
  - "nc"
  - "netcat" 
  - "telnet"
  - "ftp"
  - "ssh"
  - "sshd"
  - "su"
  - "sudo"

# Directories to monitor for file system changes
monitored_directories:
  - "/etc"
  - "/usr/bin"
  - "/usr/sbin"
  - "/bin"
  - "/sbin"

# Container security checks
security_checks:
  check_root_user: true
  check_privileged_mode: true
  check_docker_socket_mount: true
  check_sensitive_mounts: true
  check_network_exposure: true
  check_capabilities: true

# Behavioral analysis settings
behavioral_analysis_config:
  baseline_period: 300  # seconds to establish baseline
  deviation_threshold: 2.0  # standard deviations for anomaly detection
  learning_period: 86400    # seconds to learn normal behavior (24 hours)

# Network monitoring settings
network_monitoring_config:
  monitor_interfaces: ["eth0", "docker0"]
  packet_sampling_rate: 0.1  # Sample 10% of packets
  suspicious_ports: [22, 23, 135, 445, 1433, 3389]
  geo_ip_blocking: false

# File system monitoring settings
file_monitoring_config:
  ignore_patterns:
    - "*.tmp"
    - "*.log"
    - "*.cache"
    - "/proc/*"
    - "/sys/*"
    - "/dev/*"
  
  critical_files:
    - "/etc/passwd"
    - "/etc/shadow"
    - "/etc/sudoers"
    - "/etc/hosts"
    - "/root/.ssh/*"
    - "/home/*/.ssh/*"

# Compliance frameworks
compliance:
  cis_docker_benchmark: true
  nist_cybersecurity_framework: true
  pci_dss: false
  hipaa: false
  gdpr: true

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  destination: "/app/logs/security-monitor.log"
  max_size_mb: 100
  backup_count: 5

# Metrics and monitoring
metrics:
  enabled: true
  prometheus_port: 9090
  influxdb_url: null
  custom_metrics:
    - "container_security_events_total"
    - "container_resource_anomalies_total"
    - "container_process_violations_total"
    - "container_network_anomalies_total"