// Centralized icon exports with direct path imports for better tree-shaking
// This reduces bundle size by avoiding the full icon index parsing

// Outline icons (24x24)
export { default as ArrowDownTrayIcon } from '@heroicons/react/24/outline/ArrowDownTrayIcon'
export { default as ArrowLeftIcon } from '@heroicons/react/24/outline/ArrowLeftIcon'
export { default as ArrowPathIcon } from '@heroicons/react/24/outline/ArrowPathIcon'
export { default as ArrowTrendingUpIcon } from '@heroicons/react/24/outline/ArrowTrendingUpIcon'
export { default as BanknotesIcon } from '@heroicons/react/24/outline/BanknotesIcon'
export { default as BriefcaseIcon } from '@heroicons/react/24/outline/BriefcaseIcon'
export { default as CalendarIcon } from '@heroicons/react/24/outline/CalendarIcon'
export { default as ChartBarIcon } from '@heroicons/react/24/outline/ChartBarIcon'
export { default as CheckCircleIcon } from '@heroicons/react/24/outline/CheckCircleIcon'
export { default as ClockIcon } from '@heroicons/react/24/outline/ClockIcon'
export { default as CogIcon } from '@heroicons/react/24/outline/CogIcon'
export { default as CreditCardIcon } from '@heroicons/react/24/outline/CreditCardIcon'
export { default as CurrencyDollarIcon } from '@heroicons/react/24/outline/CurrencyDollarIcon'
export { default as DocumentTextIcon } from '@heroicons/react/24/outline/DocumentTextIcon'
export { default as ExclamationTriangleIcon } from '@heroicons/react/24/outline/ExclamationTriangleIcon'
export { default as EyeIcon } from '@heroicons/react/24/outline/EyeIcon'
export { default as EyeSlashIcon } from '@heroicons/react/24/outline/EyeSlashIcon'
export { default as FunnelIcon } from '@heroicons/react/24/outline/FunnelIcon'
export { default as HomeIcon } from '@heroicons/react/24/outline/HomeIcon'
export { default as LockClosedIcon } from '@heroicons/react/24/outline/LockClosedIcon'
export { default as MapPinIcon } from '@heroicons/react/24/outline/MapPinIcon'
export { default as MegaphoneIcon } from '@heroicons/react/24/outline/MegaphoneIcon'
export { default as PauseIcon } from '@heroicons/react/24/outline/PauseIcon'
export { default as PhoneIcon } from '@heroicons/react/24/outline/PhoneIcon'
export { default as PlayIcon } from '@heroicons/react/24/outline/PlayIcon'
export { default as PlusIcon } from '@heroicons/react/24/outline/PlusIcon'
export { default as ShieldCheckIcon } from '@heroicons/react/24/outline/ShieldCheckIcon'
export { default as StarIcon } from '@heroicons/react/24/outline/StarIcon'
export { default as UserIcon } from '@heroicons/react/24/outline/UserIcon'
export { default as UserGroupIcon } from '@heroicons/react/24/outline/UserGroupIcon'
export { default as XMarkIcon } from '@heroicons/react/24/outline/XMarkIcon'

// Solid icons (24x24)
export { default as CheckCircleIconSolid } from '@heroicons/react/24/solid/CheckCircleIcon'
export { default as ExclamationCircleIconSolid } from '@heroicons/react/24/solid/ExclamationCircleIcon'
export { default as ExclamationTriangleIconSolid } from '@heroicons/react/24/solid/ExclamationTriangleIcon'
export { default as InformationCircleIconSolid } from '@heroicons/react/24/solid/InformationCircleIcon'
export { default as XCircleIconSolid } from '@heroicons/react/24/solid/XCircleIcon'
